# Generated by Django 4.2.30 on 2026-05-19 04:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_type', models.CharField(blank=True, choices=[('onboarding', 'Onboarding'), ('evaluation', 'Evaluation'), ('review', 'Review'), ('push_forward', 'Push Forward'), ('user_directed', 'User Directed')], max_length=32)),
                ('evaluation_phase', models.CharField(blank=True, max_length=32)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('summary', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discord_id', models.CharField(max_length=64, unique=True)),
                ('display_name', models.CharField(blank=True, max_length=128)),
                ('native_language', models.CharField(blank=True, max_length=64)),
                ('interests', models.TextField(blank=True)),
                ('why_learning', models.TextField(blank=True)),
                ('target_use', models.TextField(blank=True)),
                ('estimated_cefr_level', models.CharField(blank=True, max_length=4)),
                ('reminder_enabled', models.BooleanField(default=True)),
                ('reminder_schedule', models.JSONField(default=dict)),
                ('onboarding_complete', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SessionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('quiz', 'Quiz Question'), ('reading', 'Reading'), ('listening', 'Listening'), ('conversation', 'Conversation'), ('written_production', 'Written Production'), ('voice', 'Voice'), ('correction', 'Error Correction'), ('system', 'System')], max_length=32)),
                ('dimension', models.CharField(blank=True, choices=[('listening', 'Listening'), ('reading', 'Reading'), ('spoken_interaction', 'Spoken Interaction'), ('spoken_production', 'Spoken Production'), ('writing', 'Writing')], max_length=32)),
                ('skill_id', models.CharField(blank=True, max_length=64)),
                ('content', models.TextField()),
                ('user_response', models.TextField(blank=True)),
                ('score_delta', models.IntegerField(blank=True, null=True)),
                ('error_logged', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='learner.session')),
            ],
        ),
        migrations.AddField(
            model_name='session',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='learner.user'),
        ),
        migrations.CreateModel(
            name='SkillScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_id', models.CharField(max_length=64)),
                ('mode', models.CharField(choices=[('listening', 'Listening'), ('reading', 'Reading'), ('spoken_interaction', 'Spoken Interaction'), ('spoken_production', 'Spoken Production'), ('writing', 'Writing')], max_length=32)),
                ('score', models.IntegerField(choices=[(0, 'Untested'), (1, 'Beginner'), (2, 'Developing'), (3, 'Confident'), (4, 'Mastered')], default=0)),
                ('last_tested_at', models.DateTimeField(blank=True, null=True)),
                ('next_review_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_scores', to='learner.user')),
            ],
            options={
                'unique_together': {('user', 'skill_id', 'mode')},
            },
        ),
        migrations.CreateModel(
            name='EvaluationProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.CharField(choices=[('session1', 'Session 1: Quiz + Freeform'), ('listening', 'Listening Comprehension'), ('speaking', 'Speaking'), ('reading', 'Reading Comprehension'), ('translation', 'Translation'), ('written_production', 'Written Production')], max_length=32)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_phases', to='learner.user')),
            ],
            options={
                'unique_together': {('user', 'phase')},
            },
        ),
    ]
