# Generated by Django 4.2.30 on 2026-05-21 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='instruction_language',
            field=models.CharField(choices=[('auto', 'Auto'), ('english', 'English'), ('spanish', 'Spanish')], default='auto', max_length=10),
        ),
        migrations.AlterField(
            model_name='sessionevent',
            name='event_type',
            field=models.CharField(choices=[('quiz', 'Quiz Question'), ('reading', 'Reading'), ('listening', 'Listening'), ('conversation', 'Conversation'), ('written_production', 'Written Production'), ('voice', 'Voice'), ('correction', 'Error Correction'), ('system', 'System'), ('menu', 'Menu'), ('redirect', 'Redirect'), ('meta', 'Meta')], max_length=32),
        ),
    ]
