# Generated by Django 4.2.30 on 2026-05-21 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learner', '0002_user_instruction_language_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=128)),
                ('category', models.CharField(max_length=64)),
                ('confidence', models.FloatField(default=0.9)),
                ('mention_count', models.IntegerField(default=1)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_reinforced_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_interests', to='learner.user')),
            ],
            options={
                'unique_together': {('user', 'topic')},
            },
        ),
    ]
