# Generated by Django 4.2.30 on 2026-05-21 23:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learner', '0003_userinterest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_id', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('cefr_level', models.CharField(max_length=4)),
                ('description', models.TextField(blank=True)),
                ('order', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('prerequisites', models.ManyToManyField(blank=True, related_name='unlocks', to='learner.skill')),
                ('replaces', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replaced_by', to='learner.skill')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AlterField(
            model_name='session',
            name='session_type',
            field=models.CharField(blank=True, choices=[('onboarding', 'Onboarding'), ('srs_review', 'SRS Review'), ('new_skill', 'New Skill'), ('vocab_sprint', 'Vocabulary Sprint'), ('conversation', 'Conversation'), ('reading', 'Reading'), ('writing', 'Writing'), ('evaluation', 'Evaluation'), ('review', 'Review'), ('push_forward', 'Push Forward'), ('user_directed', 'User Directed')], max_length=32),
        ),
        migrations.CreateModel(
            name='SkillScoreEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('listening', 'Listening'), ('reading', 'Reading'), ('spoken_interaction', 'Spoken Interaction'), ('spoken_production', 'Spoken Production'), ('writing', 'Writing')], max_length=32)),
                ('score', models.IntegerField()),
                ('scored_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='score_events', to='learner.session')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_events', to='learner.skill')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_score_events', to='learner.user')),
            ],
            options={
                'ordering': ['scored_at'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='skillscore',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='skillscore',
            name='skill_id',
        ),
        migrations.AddField(
            model_name='skillscore',
            name='skill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='learner.skill'),
        ),
        migrations.AlterUniqueTogether(
            name='skillscore',
            unique_together={('user', 'skill', 'mode')},
        ),
        migrations.CreateModel(
            name='SessionSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_skills', to='learner.session')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_skills', to='learner.skill')),
            ],
            options={
                'unique_together': {('session', 'skill')},
            },
        ),
    ]
