# Generated by Django 4.2.30 on 2026-05-22 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learner', '0004_skill_alter_session_session_type_skillscoreevent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='current_phase',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='session',
            name='phase_turns_completed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='session',
            name='target_skill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='targeted_sessions', to='learner.skill'),
        ),
    ]
