# Generated by Django 4.2.30 on 2026-05-24 02:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learner', '0005_session_current_phase_session_phase_turns_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='quiz_state',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format', models.CharField(choices=[('multiple_choice', 'Multiple Choice'), ('freeform_word', 'Freeform Word'), ('freeform_response', 'Freeform Response')], max_length=20)),
                ('question_text', models.TextField()),
                ('options', models.JSONField(blank=True, null=True)),
                ('correct_answer', models.TextField()),
                ('rubric', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_questions', to='learner.skill')),
            ],
        ),
    ]
