# Generated by Django 4.2.30 on 2026-05-30 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learner', '0006_quizquestion_session_quiz_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='messenger_psid',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='discord_id',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
