# Generated by Django 4.2.30 on 2026-06-13 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learner', '0007_add_messenger_psid'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='translate_mode_entered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
