# Generated by Django 4.2.30 on 2026-08-11 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learner', '0008_user_translate_mode_entered_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='resume_pending',
            field=models.BooleanField(default=False),
        ),
    ]
