# Generated by Django 4.2.30 on 2026-08-12 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learner', '0009_user_resume_pending'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_message', models.TextField(help_text='Raw user message that contained the feedback.')),
                ('interpretation', models.TextField(help_text="LLM's one-sentence paraphrase of what the user is flagging.")),
                ('resolved', models.BooleanField(default=False)),
                ('resolution_note', models.TextField(blank=True, help_text='Optional note when reviewing/closing this.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('anchor_event', models.ForeignKey(blank=True, help_text='The Luz turn the user was reacting to (usually the most recent assistant message).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback', to='learner.sessionevent')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='learner.session')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
