# Generated by Django 4.2.30 on 2026-08-25 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learner', '0010_sessionfeedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='session_type',
            field=models.CharField(blank=True, choices=[('onboarding', 'Onboarding'), ('srs_review', 'SRS Review'), ('new_skill', 'New Skill'), ('vocab_sprint', 'Vocabulary Sprint'), ('conversation', 'Conversation'), ('reading', 'Reading'), ('writing', 'Writing'), ('review', 'Review')], max_length=32),
        ),
    ]
