# Generated by Django 4.2.30 on 2026-08-26 00:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learner', '0011_alter_session_session_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElicitationAsk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.CharField(max_length=64)),
                ('category', models.CharField(max_length=32)),
                ('asked_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elicitation_asks', to='learner.user')),
            ],
            options={
                'unique_together': {('user', 'question_id')},
            },
        ),
    ]
