# Generated by Django 4.2.30 on 2026-08-26 01:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learner', '0012_elicitationask'),
    ]

    operations = [
        migrations.CreateModel(
            name='LexItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('es', models.CharField(max_length=128)),
                ('en', models.CharField(max_length=256)),
                ('pos', models.CharField(blank=True, max_length=32)),
                ('gender', models.CharField(blank=True, choices=[('m', 'Masculine'), ('f', 'Feminine')], max_length=1)),
                ('analyzable', models.BooleanField(default=True)),
                ('note', models.TextField(blank=True)),
                ('packs', models.CharField(blank=True, max_length=256)),
                ('cefr_level', models.CharField(blank=True, max_length=4)),
                ('active', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lex_items', to='learner.user')),
            ],
            options={
                'ordering': ['cefr_level', 'es'],
            },
        ),
        migrations.CreateModel(
            name='UserWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('introduced', 'Introduced'), ('practiced', 'Practiced'), ('known', 'Known')], default='introduced', max_length=16)),
                ('times_seen', models.IntegerField(default=0)),
                ('times_produced', models.IntegerField(default=0)),
                ('first_taught_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('next_due_at', models.DateTimeField(blank=True, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_words', to='learner.lexitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='words', to='learner.user')),
            ],
            options={
                'ordering': ['next_due_at'],
                'unique_together': {('user', 'item')},
            },
        ),
        migrations.AddConstraint(
            model_name='lexitem',
            constraint=models.UniqueConstraint(condition=models.Q(('owner__isnull', True)), fields=('es',), name='unique_core_lexitem'),
        ),
        migrations.AddConstraint(
            model_name='lexitem',
            constraint=models.UniqueConstraint(condition=models.Q(('owner__isnull', False)), fields=('es', 'owner'), name='unique_owned_lexitem'),
        ),
    ]
