# Generated by Django 4.2.30 on 2026-08-26 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learner', '0013_lexitem_userword_lexitem_unique_core_lexitem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='session_type',
            field=models.CharField(blank=True, choices=[('onboarding', 'Onboarding'), ('srs_review', 'SRS Review'), ('new_skill', 'New Skill'), ('conversation', 'Conversation'), ('reading', 'Reading'), ('writing', 'Writing')], max_length=32),
        ),
    ]
