# Generated by Django 4.2.30 on 2026-08-28 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learner', '0014_alter_session_session_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='userword',
            name='interval_index',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userword',
            name='times_failed',
            field=models.IntegerField(default=0),
        ),
    ]
