# Generated by Django 4.2.30 on 2026-09-06 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learner', '0015_userword_interval_index_userword_times_failed'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='phase_questions_asked',
            field=models.IntegerField(default=0),
        ),
    ]
